# -*- coding: utf-8 -*-
#
# Form implementation generated from reading ui file 'OneDrive - Linköpings universitet/Programmering/TSEA56/Designer_gui_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import paho.mqtt.client as mqtt
from PyQt5 import QtCore, QtGui, QtWidgets
import time
import multiprocessing
import keyboard

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(986, 672)

        self.update_time_bool = False
        self.current_time = "0"
        self.start = time.time()

        self.distance_to_obj = "0"
        self.car_speed_data = 0
        self.type_of_mode = "Manual"
        self.qData = multiprocessing.Queue()

        self.is_driving = False
        
        self.speed = 0
        self.steering = 52
        self.breaking = 0

        self.obst_det_head = QtWidgets.QLabel(Dialog)
        self.obst_det_head.setGeometry(QtCore.QRect(140, 20, 131, 16))
        self.obst_det_head.setObjectName("obst_det_head")

        self.obst_det_bool = QtWidgets.QLabel(Dialog)
        self.obst_det_bool.setGeometry(QtCore.QRect(30, 60, 131, 16))
        self.obst_det_bool.setObjectName("obst_det_bool")

        self.obst_dist = QtWidgets.QLabel(Dialog)
        self.obst_dist.setGeometry(QtCore.QRect(210, 60, 131, 16))
        self.obst_dist.setObjectName("obst_dist")

        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(30, 90, 151, 31))
        self.textBrowser.setObjectName("textBrowser")

        self.distance_display = QtWidgets.QTextBrowser(Dialog)
        self.distance_display.setGeometry(QtCore.QRect(210, 90, 151, 31))
        self.distance_display.setObjectName("distance_display")

        self.drive_mode_head = QtWidgets.QLabel(Dialog)
        self.drive_mode_head.setGeometry(QtCore.QRect(20, 180, 91, 16))
        self.drive_mode_head.setObjectName("drive_mode_head")

        #manual mode
        self.manual_mode = QtWidgets.QPushButton(Dialog)
        self.manual_mode.setGeometry(QtCore.QRect(20, 220, 161, 26))
        self.manual_mode.setObjectName("manual_mode")

        #semi-automatic
        self.semi_auto_mode = QtWidgets.QPushButton(Dialog)
        self.semi_auto_mode.setGeometry(QtCore.QRect(20, 270, 161, 31))
        self.semi_auto_mode.setObjectName("semi_auto_mode")

        #automatic
        self.auto_mode = QtWidgets.QPushButton(Dialog)
        self.auto_mode.setGeometry(QtCore.QRect(20, 320, 161, 31))
        self.auto_mode.setObjectName("auto_mode")

        #start button to initate car
        self.start_car = QtWidgets.QPushButton(Dialog)
        self.start_car.setGeometry(QtCore.QRect(240, 230, 141, 51))
        self.start_car.setStyleSheet("background-color: green")
        self.start_car.setObjectName("start_car")

        #stop button
        self.stop_car = QtWidgets.QPushButton(Dialog)
        self.stop_car.setGeometry(QtCore.QRect(240, 300, 141, 51))
        self.stop_car.setStyleSheet("background-color: red")
        self.stop_car.setObjectName("stop_car")

        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(110, 550, 81, 26))
        self.pushButton_4.setObjectName("pushButton_4")

        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(110, 610, 81, 26))
        self.pushButton_5.setObjectName("pushButton_5")

        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 580, 81, 26))
        self.pushButton_6.setObjectName("pushButton_6")

        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(200, 580, 81, 26))
        self.pushButton_7.setObjectName("pushButton_7")

        self.send_command = QtWidgets.QPushButton(Dialog)
        self.send_command.setGeometry(QtCore.QRect(280, 425, 120, 30))
        self.send_command.setObjectName("send_command")

        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(110, 510, 101, 16))
        self.label_5.setObjectName("label_5")

        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(30, 410, 241, 64))
        self.textEdit.setObjectName("textEdit")

        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(100, 380, 131, 16))
        self.label_6.setObjectName("label_6")

        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(650, 20, 81, 16))
        self.label_7.setObjectName("label_7")

        self.time_label = QtWidgets.QLabel(Dialog)
        self.time_label.setGeometry(QtCore.QRect(490, 50, 151, 16))
        self.time_label.setObjectName("time_label")

        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(490, 90, 151, 16))
        self.label_9.setObjectName("label_9")

        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(490, 130, 151, 16))
        self.label_10.setObjectName("label_10")

        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(490, 170, 151, 16))
        self.label_11.setObjectName("label_11")

        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(490, 210, 151, 16))
        self.label_12.setObjectName("label_12")

        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(490, 250, 151, 16))
        self.label_13.setObjectName("label_13")

        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(490, 290, 151, 16))
        self.label_14.setObjectName("label_14")

        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(490, 330, 151, 16))
        self.label_15.setObjectName("label_15")

        self.time_display = QtWidgets.QTextBrowser(Dialog)
        self.time_display.setGeometry(QtCore.QRect(670, 50, 301, 31))
        self.time_display.setObjectName("time_display")

        self.textBrowser_4 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_4.setGeometry(QtCore.QRect(670, 90, 301, 31))
        self.textBrowser_4.setObjectName("textBrowser_4")

        self.throttle_display = QtWidgets.QTextBrowser(Dialog)
        self.throttle_display.setGeometry(QtCore.QRect(670, 130, 301, 31))
        self.throttle_display.setObjectName("throttle_display")

        self.textBrowser_6 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_6.setGeometry(QtCore.QRect(670, 210, 301, 31))
        self.textBrowser_6.setObjectName("textBrowser_6")

        self.textBrowser_7 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_7.setGeometry(QtCore.QRect(670, 250, 301, 31))
        self.textBrowser_7.setObjectName("textBrowser_7")

        self.textBrowser_8 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_8.setGeometry(QtCore.QRect(670, 170, 301, 31))
        self.textBrowser_8.setObjectName("textBrowser_8")

        self.textBrowser_11 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_11.setGeometry(QtCore.QRect(670, 290, 301, 31))
        self.textBrowser_11.setObjectName("textBrowser_11")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.distance_display.setText(str(self.distance_to_obj))


        self.connect_buttons()

        self.mqtt_init()

        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.update_time)
        self.timer.start(70)  # update every 1000 milliseconds (1 second)

        self.messagetimer = QtCore.QTimer()
        self.messagetimer.timeout.connect(self.updatedata)
        self.messagetimer.start(100)

        self.drivingtimer = QtCore.QTimer()
        self.drivingtimer.timeout.connect(self.drive_function)
        self.drivingtimer.start(10)

    def drive_function(self):

        if ((self.type_of_mode == "Manual") & (self.is_driving)):
            hotkey = keyboard.get_hotkey_name()
            if hotkey == "uppil":
                if self.speed <= 251:
                    self.speed += 2
                    self.mqtt_client.publish("speed", self.speed)
                
                print(self.speed)
            if hotkey == "nedpil":
                if self.speed >= 2:
                    self.speed -= 2
                    self.mqtt_client.publish("speed", self.speed)
                print(self.speed)
            if hotkey == "högerpil":
                if self.steering <= 118:
                    self.steering += 2
                    self.mqtt_client.publish("steering", self.steering)
                print(self.steering)
            if hotkey == "vänsterpil":
                if self.steering >= 2:
                    self.steering -= 2
                    self.mqtt_client.publish("steering", self.steering)
                    print(self.steering)

            
            if hotkey == "space":
                self.speed = 0
                self.mqtt_client.publish("speed", self.speed)
            if hotkey == "b":
                if self.breaking == 0:
                    self.breaking = 1
                    self.speed = 0
                    self.mqtt_client.publish("breaking", self.breaking)
                    self.mqtt_client.publish("speed", self.speed)               
            if hotkey == "g": 
                if self.breaking == 1:                
                    self.breaking = 0
                    print(self.breaking)
                    self.mqtt_client.publish("breaking", self.breaking)

    def update_time(self):
        # get the current time and format it as a string
        if self.update_time_bool:
            self.current_time = (str(round(time.time() - self.start,2)))
        # set the text of the time_label widget to the current time
        else:
            #start = time.time()
            pass
        self.time_display.setText(self.current_time)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Very fast taxicar, vroom vroom"))

        self.obst_det_head.setText(_translate("Dialog", "Obstacle detection:"))

        self.obst_det_bool.setText(_translate("Dialog", "Obstacle detected"))

        self.obst_dist.setText(_translate("Dialog", "Distance to obstacle"))

        self.drive_mode_head.setText(_translate("Dialog", "Drive mode:"))

        self.manual_mode.setText(_translate("Dialog", "Manual mode"))
        self.semi_auto_mode.setText(_translate("Dialog", "Semi-automatic mode"))
        self.auto_mode.setText(_translate("Dialog", "Automatic mode"))
        self.start_car.setText(_translate("Dialog", "START"))
        self.stop_car.setText(_translate("Dialog", "STOP"))
        self.pushButton_4.setText(_translate("Dialog", "Up"))
        self.pushButton_5.setText(_translate("Dialog", "Down"))
        self.pushButton_6.setText(_translate("Dialog", "Left"))
        self.pushButton_7.setText(_translate("Dialog", "Right"))
        self.send_command.setText(_translate("Dialog", "Send command"))

        self.label_5.setText(_translate("Dialog", "Manual control"))
        self.label_6.setText(_translate("Dialog", "Command input"))
        self.label_7.setText(_translate("Dialog", "Drive info"))
        self.time_label.setText(_translate("Dialog", "Time:"))
        self.label_9.setText(_translate("Dialog", "Distance:"))
        self.label_10.setText(_translate("Dialog", "Throttle:"))
        self.label_11.setText(_translate("Dialog", "Bearing:"))
        self.label_12.setText(_translate("Dialog", "Current road segment:"))
        self.label_13.setText(_translate("Dialog", "Lateral position:"))
        self.label_14.setText(_translate("Dialog", "Planned route:"))
        self.label_15.setText(_translate("Dialog", "Map:"))


    def connect_buttons(self):
        self.manual_mode.clicked.connect(self.on_manual_mode_click)
        self.semi_auto_mode.clicked.connect(self.on_semi_auto_mode_click)
        self.auto_mode.clicked.connect(self.on_auto_mode_click)
        self.send_command.clicked.connect(self.on_send_command)

        #start and stop
        self.start_car.clicked.connect(self.on_start_car_click)
        self.stop_car.clicked.connect(self.on_stop_car_click)

    def on_manual_mode_click(self):
        # This method is called when manual_mode is clicked
        if not self.is_driving:
            self.mqtt_client.publish("mode", 1)
            self.type_of_mode = "Manual"
            print(self.type_of_mode)

    def on_semi_auto_mode_click(self):
        # This method is called when semi_auto_mode is clicked
        if not self.is_driving:
            self.mqtt_client.publish("mode", 2)
            self.type_of_mode = "Semi-automatic"
            print(self.type_of_mode)
        
    def on_auto_mode_click(self):
        # This method is called when auto_mode is clicked
        if not self.is_driving:
            self.mqtt_client.publish("mode", 3)
            self.type_of_mode = "Automatic"
            print(self.type_of_mode)
    
    def on_send_command(self):
        # This method is called when manual_mode is clicked
        self.mqtt_client.publish("data/command")
        print(self.textEdit.toPlainText())

    def on_start_car_click(self):
        #starts car
        self.update_time_bool = 1
        self.start = time.time()   
        self.is_driving = True 
        print("START")

    def on_stop_car_click(self):
        #stops car
        self.current_time = "0"
        self.update_time_bool = 0
        self.is_driving = False
        print("STOP")

    def mqtt_init(self):
    #initate connection
        try:
            broker_ip = "10.241.242.186"
            broker_port = 1883
            self.mqtt_client = mqtt.Client()
            self.mqtt_client.username_pw_set("tsea56G09", "mindset")
            self.mqtt_client.connect(broker_ip, broker_port)
            self.mqtt_client.subscribe("data/distance")
            self.mqtt_client.subscribe("data/speed")
            self.mqtt_client.loop_start()
            self.mqtt_client.on_message = self.on_message
        except: 
            print("Failed to setup connection")


    def on_message(self, client, userdata, message):
        m = str(message.payload.decode("utf-8"))
        t = message.topic
        self.qData.put((t,m))
        
    def updatedata(self):
        if not self.qData.empty():
            message = self.qData.get()
            if message[0] == "data/speed":
                #print ("Speed recieved")
                pass
            if message[0] == "data/distance":
                #print ("Distance recieved")
                self.distance_to_obj = message[1]
                print(self.distance_to_obj)
                self.distance_display.setText(str(self.distance_to_obj))

            #print(self.qData.get()[1])      
        
        
    #def time_printer():
    #    self.time_display.


if __name__ == "__main__":
    import sys
    #start = time.time()
    app = QtWidgets.QApplication(sys.argv)

    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
